#volumes:
#  db-volume:

x-backend: &backend
  build:
    context: .
    dockerfile: _docker/backend/Dockerfile
  image: backend
  volumes:
    - ./backend:/backend

#x-frontend: &frontend
#  build:
#    context: .
#    dockerfile: _docker/frontend/Dockerfile
#  image: frontend
#  volumes:
#    - ./frontend:/frontend


services:
#  postgres:
#    image: postgres:latest
#    restart: unless-stopped
#    volumes:
#      - db-volume:/var/lib/postgresql/data
#    env_file:
#      - backend/.env
#    ports:
#      - 5432:5432

  backend:
    <<: *backend
    command: uvicorn app.app:app --host 0.0.0.0 --port 8080 --workers 1 --log-level debug --reload
    working_dir: /backend
    expose:
      - 8080
    env_file: backend/.env
#    environment:
#      - POSTGRES_HOST=postgres
    ports:
      - 8080:8080
#    depends_on:
#      - postgres
